title: Výuka na UP
description: Informační stránky
theme: just-the-docs

url: https://bdodova.github.io/

# Enable or disable the site search
search_enabled: true

collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  thv2-2022-23:
    permalink: "/:collection/:path/"
    output: true
  thv2-2023-24:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    thv2-2022-23:
      name: THV2 2022/23
      #nav_exclude: true
      #search_exclude: true
    thv2-2023-24:
      name: THV2 2023/24
