title: Výuka
description: Stránky s informacemi o vyučovaných předmětech
theme: just-the-docs

url: https://bdodova.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
